---
abstract: 'ASCII/Markdown table exporter'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Exporter-Table
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0.9
  perl: v5.10.0
resources:
  bugtracker: https://github.com/nichtich/Catmandu-Exporter-Table/issues
  homepage: https://github.com/nichtich/Catmandu-Exporter-Table
  repository: https://github.com/nichtich/Catmandu-Exporter-Table.git
version: v0.1.1
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
